version: "3.6"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_URL: "postgres://ntkfzzie:DjP5y_uKB_nTsguv1msAdC197UzBu26o@tyke.db.elephantsql.com/ntkfzzie"
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/data/postgres
volumes:
  progresDB:
